name: offer_show
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shelf_proxy: ^1.0.0
  shelf: ^1.1.4
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  flutter_easyloading: ^3.0.0
  loading: ^1.0.2
  direct_select: ^2.0.0
  fluttertoast: ^8.0.6
  flutter_easyrefresh: ^2.2.1
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_svg: ^0.21.0+1
  cupertino_icons: ^1.0.2
  crypto: ^3.0.1
  dio: ^4.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/img/logo.svg
    - lib/img/search.svg
    - lib/img/home.svg