name: offer_show
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  fluttertoast: ^8.0.6
  flutter_easyrefresh: ^2.2.1
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  flutter_svg: ^0.21.0+1
  cupertino_icons: ^1.0.2
  crypto: ^3.0.1
  dio: ^4.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/img/logo.svg
    - lib/img/share.svg
    - lib/img/me-agreement.svg
    - lib/img/me-poster.svg
    - lib/img/me-discuss.svg
    - lib/img/me-feedback.svg
    - lib/img/salary-location.svg
    - lib/img/salary-right.svg
    - lib/img/detail-job.svg
    - lib/img/detail-company.svg
    - lib/img/detail-city.svg
    - lib/img/detail-rightBottom.svg
    - lib/img/detail-info.svg
    - lib/img/detail-skelon.svg
    - lib/img/salary-more.svg
    - lib/img/detail-collect.svg
    - lib/img/detail-feedback.svg
    - lib/img/detail-like.svg
    - lib/img/detail-unlike.svg
    - lib/img/empty.svg