name: offer_show
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  characters: ^1.2.0
  flutter_vibrate: ^1.3.0
  vibration: ^1.7.3
  image_picker: ^0.8.4+10
  file_picker: ^4.5.0
  flutter:
    sdk: flutter
  photo_view: ^0.10.2
  provider: 
  shared_preferences: ^2.0.5
  flutter_easyloading: ^3.0.0
  fluttertoast: ^8.0.6
  flutter_svg: ^0.21.0+1
  dio: ^4.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.20
  card_swiper: ^2.0.1
  heic_to_jpg: ^0.2.0
  image_gallery_saver: ^1.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/img/logo.svg
    - lib/img/search.svg
    - lib/img/search_blue.svg
    - lib/img/home.svg
    - lib/img/banner.svg
    - lib/img/like_blue.svg
    - lib/img/like_grey.svg
    - lib/img/comment.svg
    - lib/img/right_arrow.svg
    - lib/img/more.svg
    - lib/img/right_arrow_grey.svg
    - lib/img/topic_detail_more.svg
    - lib/img/topic_water.svg
    - lib/img/topic_collect.svg
    - lib/img/detail_sort.svg
    - lib/img/detail_like.svg
    - lib/img/detail_like_blue.svg
    - lib/img/detail_comment_more.svg
    - lib/img/search_filter.svg
    - lib/img/empty.png
    - lib/img/to_top.svg
    - lib/img/topic_emoji.svg
    - lib/img/topic_@.svg
    - lib/img/topic_picture.svg
    - lib/img/topic_attach.svg
    - lib/collect_btn/0-all.svg
    - lib/collect_btn/1-loss.svg
    - lib/collect_btn/2-second.svg
    - lib/img/home/1.svg
    - lib/img/home/2.svg
    - lib/img/home/3.svg
    - lib/img/home/4.svg
    - lib/img/home/5.svg
    - lib/img/square/1.svg
    - lib/img/square/2.svg
    - lib/img/square/3.svg
    - lib/img/square/4.svg
    - lib/img/square/5.svg
    - lib/img/square/6.svg